"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# command_timeout = 1000

format = """
╭─ $directory\
$git_branch $git_status\
$fill\
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
$cmd_duration
╰─ $hostname$character"""

right_format = """

"""
# continuation_prompt = '▶▶ '

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

# Shows the hostname
[hostname]
ssh_only = true
format = '[$hostname](bold yellow)'
disabled = false
ssh_symbol = " "

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = '197'
read_only = '  '
style = 'cyan'
format = '[$path]($style)[$read_only]($read_only_style) '

[fill]
symbol = ' '

[cmd_duration]
min_time = 3_000
style = '101'
format = '[$duration]($style)'

# ---



# Shows current git branch
[git_branch]
symbol = ""
format = '[$symbol$branch]($style)'
style = 'green'
# symbol = " "
# truncation_length = 4

# Shows current git status
[git_status]
style = 'green'
format = '[$ahead_behind $stashed $conflicted $staged $modified $untracked]($style) '

behind = '⇣${count}'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = ''

stashed = '[*${count}](green)'
conflicted = '[~${count}](red)'
staged = '[+${count}](yellow)'
modified = '[!${count}](yellow)'
untracked = '[?${count}](cyan)'

# renamed = '襁 '
# deleted = ' '


# ---
[c]
symbol = " "

[conda]
symbol = " "

[docker_context]
symbol = " "

[lua]
symbol = " "

[package]
symbol = "󰏗 "

[python]
style = 'cyan'
pyenv_prefix = ""
format = '[${symbol}(\($virtualenv\) )]($style)'
symbol = " "
pyenv_version_name = true
